# https://taskfile.dev

version: '3'

output: prefixed

tasks:
  default:
    silent: true
    interactive: true
    cmds:
      - cmd: task --list
      - cmd: printf "\nRun \"task --help\" for more information.\n"

  check:
    desc: >-
      Simulates all steps of the "QA" job executed during the pull request CI workflow
    deps:
      - fmt
      - test
      - lint
      - vet
      - build

  test:
    desc: "Runs unit tests and updates the HTML coverage report"
    run: once
    prefix: "test output"
    cmds:
      - go test -race -covermode=atomic -coverprofile=cover.out {{ .CLI_ARGS }} ./...
      - task: coverage-report-html
    sources:
      - ./**/*.go
      - ./Taskfile.yml
      - ./go.mod
      - ./go.sum

  coverage-report-html:
    desc: "Writes an HTML coverage report to cover.html"
    cmds:
      - go tool cover -html=cover.out -o cover.html
    sources:
      - ./cover.out
    generates:
      - ./cover.html

  lint:
    desc: "Runs the staticcheck linter utility"
    vars:
      FORMAT: '{{ default "stylish" .FORMAT }}'
    cmds:
      - "staticcheck -f {{ .FORMAT }} ./..."
    sources:
      - ./**/*.go

  generate:
    desc: "Discovers and runs all go:generate directives for the entire project"
    cmds:
      - go generate ./...

  fmt:
    desc: Runs `go fmt` for the entire project
    cmds:
      - go fmt ./...
    sources:
      - ./**/*.go

  vet:
    desc: Runs `go vet` for the entire project
    cmds:
      - go vet ./...
    sources:
      - ./**/*.go

  clean:
    desc: "Removes generated content from ./bin and ./build directories"
    silent: true
    cmds:
      - find ./bin -mindepth 1 -type d -exec rm -rf {} + -print
      - find ./build -mindepth 1 -type d -exec rm -rf {} + -print

  build-lambda:
    internal: true
    run: when_changed
    label: "build-{{ .LAMBDA_CMD }}"
    vars:
      BUILD_DIR: bin/{{ .LAMBDA_CMD }}
      BUILD_BIN: "{{ .BUILD_DIR }}/bootstrap"
      SOURCE: ./cmd/{{ .LAMBDA_CMD }}/...
    env:
      GOARCH: arm64
      GOOS: linux
      GOPATH:
        sh: go env GOPATH
    cmds:
      - go build -gcflags="-trimpath=$GOPATH" -ldflags="-s -w" -asmflags="-trimpath=$GOPATH" -trimpath -tags "lambda.norpc" -v -o {{ .BUILD_BIN }} {{ .SOURCE }}
      - cmd: echo {{ .BUILD_BIN }}
        silent: true
    sources:
      - ./**/*.go
      - ./Taskfile.yml
      - ./go.mod
      - ./go.sum
    generates:
      - "{{ .BUILD_BIN }}"

  build:
    desc: "Compiles all Lambda handlers"
    deps:
      - build-DownloadGrantsGovDB
      - build-SplitGrantsGovXMLDB
      - build-ExtractGrantsGovDBToXML

  build-DownloadGrantsGovDB:
    desc: Compiles DownloadGrantsGovDB
    cmds:
      - task: build-lambda
        vars:
          LAMBDA_CMD: DownloadGrantsGovDB

  build-SplitGrantsGovXMLDB:
    desc: Compiles SplitGrantsGovXMLDB
    cmds:
      - task: build-lambda
        vars:
          LAMBDA_CMD: SplitGrantsGovXMLDB
  
  build-ExtractGrantsGovDBToXML:
    desc: Complies ExtractGrantsGovDBToXML
    cmds:
      - task: build-lambda
        vars:
          LAMBDA_CMD: ExtractGrantsGovDBToXML
