name: Build

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      build-cli:
        type: boolean
        default: false
      build-lambdas:
        type: boolean
        default: false
    outputs:
      build-cli-result:
        value: ${{ jobs.build-cli.result }}
      build-lambdas-result:
        value: ${{ jobs.build-lambdas.result }}
      cli-artifacts-key:
        value: ${{ jobs.build-cli.outputs.artifacts-key }}
      cli-artifacts-path:
        value: ${{ jobs.build-cli.outputs.artifacts-path }}
      cli-checksums-sha256:
        value: ${{ jobs.build-cli.outputs.checksums-sha256 }}
      lambda-artifacts-key:
        value: ${{ jobs.build-lambdas.outputs.artifacts-key }}
      lambda-artifacts-path:
        value: ${{ jobs.build-lambdas.outputs.artifacts-path }}
      lambda-checksums-sha256:
        value: ${{ jobs.build-lambdas.outputs.checksums-sha256 }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      SOURCES_KEY: go-sources-${{ inputs.ref }}
      SOURCES_PATH: |
        ${{ github.workspace }}/cli
        ${{ github.workspace }}/cmd
        ${{ github.workspace }}/internal
        ${{ github.workspace }}/pkg
        ${{ github.workspace }}/openapi/openapi.yaml
        ${{ github.workspace }}/go.mod
        ${{ github.workspace }}/go.sum
        ${{ github.workspace }}/Taskfile.yml
    outputs:
      sources-key: ${{ env.SOURCES_KEY }}
      sources-path: ${{ env.SOURCES_PATH }}
    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            actions-results-receiver-production.githubapp.com:443
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            sum.golang.org:443
            storage.googleapis.com:443
      - uses: actions/checkout@v4
        with:
          show-progress: 'false'
          persist-credentials: 'false'
      - uses: actions/setup-go@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          go-version-file: go.mod
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x
      - name: Pre-build optimization
        run: task prebuild-lambda
      - name: Store build sources
        id: store
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SOURCES_KEY }}
          path: ${{ env.SOURCES_PATH }}

  build-lambdas:
    name: Build Lambdas
    if: needs.prepare.result == 'success' && inputs.build-lambdas
    runs-on: ubuntu-latest
    needs:
      - prepare
    env:
      ARTIFACTS_KEY: lambdas-${{ inputs.ref }}
      ARTIFACTS_PATH: ${{ github.workspace }}/bin
    outputs:
      artifacts-key: ${{ env.ARTIFACTS_KEY }}
      artifacts-path: ${{ env.ARTIFACTS_PATH }}
      checksums-sha256: ${{ steps.final-checksums.outputs.checksums }}
    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            actions-results-receiver-production.githubapp.com:443
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            sum.golang.org:443
            raw.githubusercontent.com:443
      - name: Restore Go build sources
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.prepare.outputs.sources-key }}
          path: .
      - uses: actions/setup-go@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          go-version-file: go.mod
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x
      - name: Prepare artifacts output directory
        run: |
          mkdir -p "$ARTIFACTS_PATH"
          rm -rf "$ARTIFACTS_PATH/*"
      - name: Build Lambdas
        id: build
        run: task build
      - name: Compiled checksums
        run: find bin -type f -exec sha256sum -b {} \; >> $GITHUB_STEP_SUMMARY
      - name: Run UPX
        id: pack
        uses: crazy-max/ghaction-upx@0fc45e912669ba9e8fa2b430e97c8da2a632e29b # v3.0.0
        with:
          version: 4.1.0
          files: bin/**
          args: -5 -q
      - name: Publish UPX results
        run: echo "$UPX_RESULTS" >> $GITHUB_STEP_SUMMARY
        env:
          UPX_RESULTS: ${{ steps.pack.outputs.stdout }}
      - name: Final checksums
        id: final-checksums
        run: |
          CHECKSUMS=$(find bin -type f -exec sha256sum -b {} \;)
          echo $CHECKSUMS >> $GITHUB_STEP_SUMMARY
          echo "checksums=$CHECKSUMS" >> $GITHUB_OUTPUT
      - name: Store build artifacts
        id: store
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACTS_KEY }}
          path: ${{ env.ARTIFACTS_PATH }}

  build-cli:
    name: Build CLI
    if: needs.prepare.result == 'success' && inputs.build-cli
    runs-on: ubuntu-latest
    needs:
      - prepare
    env:
      ARTIFACTS_KEY: cli-${{ inputs.ref }}
      ARTIFACTS_PATH: ${{ github.workspace }}/bin/grants-ingest
    outputs:
      artifacts-key: ${{ env.ARTIFACTS_KEY }}
      artifacts-path: ${{ env.ARTIFACTS_PATH }}
      checksums-sha256: ${{ steps.final-checksums.outputs.checksums }}
    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            actions-results-receiver-production.githubapp.com:443
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            sum.golang.org:443
            raw.githubusercontent.com:443
      - name: Restore Go build sources
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.prepare.outputs.sources-key }}
          path: .
      - uses: actions/setup-go@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          go-version-file: go.mod
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x
      - run: mkdir -p $(dirname $ARTIFACTS_PATH)
      - name: Build CLI
        id: build
        run: task build-cli
      - name: Compiled checksums
        run: sha256sum -b "$ARTIFACTS_PATH" >> $GITHUB_STEP_SUMMARY
      - name: Run UPX
        id: pack
        uses: crazy-max/ghaction-upx@0fc45e912669ba9e8fa2b430e97c8da2a632e29b # v3.0.0
        with:
          version: 4.1.0
          files: bin/**
          args: -5 -q
      - name: Publish UPX results
        run: echo "$UPX_RESULTS" >> $GITHUB_STEP_SUMMARY
        env:
          UPX_RESULTS: ${{ steps.pack.outputs.stdout }}
      - name: Final checksums
        id: final-checksums
        run: |
          CHECKSUMS=$(sha256sum -b "$ARTIFACTS_PATH")
          echo $CHECKSUMS >> $GITHUB_STEP_SUMMARY
          echo "checksums=$CHECKSUMS" >> $GITHUB_OUTPUT
      - name: Store build artifacts
        id: store
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACTS_KEY }}
          path: ${{ env.ARTIFACTS_PATH }}
